#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtricate.Web.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HomePage : Xtricate.Web.Dashboard.RazorPage
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 4 "..\..\Pages\HomePage.cshtml"
  
    Layout = new LayoutPage();
    bool first = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>Welcome to the dashboard</h3>");

        }
    }
}
#pragma warning restore 1591
