#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtricate.Web.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class InfoPage : Xtricate.Web.Dashboard.RazorPage<Xtricate.Web.Dashboard.Models.DashboardInfoViewModel>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 4 "..\..\Pages\InfoPage.cshtml"
  
    Layout = new LayoutPage();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Routes</h4>\r\n<ul>\r\n");

            
            #line 10 "..\..\Pages\InfoPage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Pages\InfoPage.cshtml"
     foreach (var route in Model.Routes)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 305), Tuple.Create("\"", 326)
            
            #line 12 "..\..\Pages\InfoPage.cshtml"
, Tuple.Create(Tuple.Create("", 312), Tuple.Create<System.Object, System.Int32>(Url.To(route)
            
            #line default
            #line hidden
, 312), false)
);

WriteLiteral(">");

            
            #line 12 "..\..\Pages\InfoPage.cshtml"
                                Write(route);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 13 "..\..\Pages\InfoPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<h4>Javascripts</h4>\r\n<ul>\r\n");

            
            #line 17 "..\..\Pages\InfoPage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Pages\InfoPage.cshtml"
     foreach (var name in Model.Javascripts)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");

            
            #line 19 "..\..\Pages\InfoPage.cshtml"
       Write(name);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 20 "..\..\Pages\InfoPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<h4>Stylesheets</h4>\r\n<ul>\r\n");

            
            #line 24 "..\..\Pages\InfoPage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Pages\InfoPage.cshtml"
     foreach (var name in Model.Stylesheets)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");

            
            #line 26 "..\..\Pages\InfoPage.cshtml"
       Write(name);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 27 "..\..\Pages\InfoPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
