#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtricate.Web.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : Xtricate.Web.Dashboard.RazorPage
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <title>");

            
            #line 6 "..\..\Pages\LayoutPage.cshtml"
      Write(Name);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 380), Tuple.Create("\"", 402)
            
            #line 10 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Url.To("/css")
            
            #line default
            #line hidden
, 387), false)
);

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <!-- Wrap all page content here -->\r\n    <div");

WriteLiteral(" id=\"wrap\"");

WriteLiteral(">\r\n\r\n        <!-- Fixed navbar -->\r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-static-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1027), Tuple.Create("\"", 1045)
            
            #line 25 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1034), Tuple.Create<System.Object, System.Int32>(Url.Home()
            
            #line default
            #line hidden
, 1034), false)
);

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"logo\"");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1097), Tuple.Create("\"", 1123)
            
            #line 26 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1103), Tuple.Create<System.Object, System.Int32>(Url.To("/img/logo")
            
            #line default
            #line hidden
, 1103), false)
);

WriteLiteral(" />\r\n                        <span>");

            
            #line 27 "..\..\Pages\LayoutPage.cshtml"
                         Write(Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1401), Tuple.Create("\"", 1416)
            
            #line 33 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1408), Tuple.Create<System.Object, System.Int32>(AppPath
            
            #line default
            #line hidden
, 1408), false)
);

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"glyphicon glyphicon-log-out\"");

WriteLiteral(@"></span>
                                Back
                            </a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>

        <!-- Begin page content -->
        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"margin-bottom: 20px;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Pages\LayoutPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list-inline credit\"");

WriteLiteral(">\r\n                <li>\r\n                    <span>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2068), Tuple.Create("\"", 2091)
            
            #line 55 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 2075), Tuple.Create<System.Object, System.Int32>(Url.To("/info")
            
            #line default
            #line hidden
, 2075), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Pages\LayoutPage.cshtml"
                       Write(Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 57 "..\..\Pages\LayoutPage.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Pages\LayoutPage.cshtml"
                              
                                var version = GetType().Assembly.GetName().Version;
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 60 "..\..\Pages\LayoutPage.cshtml"
                       Write(string.Format("{0}.{1}.{2}", version.Major, version.Minor, version.Build));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </span>\r\n                </li" +
">\r\n                <li>Time: ");

            
            #line 64 "..\..\Pages\LayoutPage.cshtml"
                     Write(DateTime.UtcNow);

            
            #line default
            #line hidden
WriteLiteral(" GMT</li>\r\n                <li>Generated: ");

            
            #line 65 "..\..\Pages\LayoutPage.cshtml"
                           Write(GenerationTime.Elapsed.TotalMilliseconds.ToString("N"));

            
            #line default
            #line hidden
WriteLiteral("ms</li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2674), Tuple.Create("\"", 2694)
            
            #line 70 "..\..\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 2680), Tuple.Create<System.Object, System.Int32>(Url.To("/js")
            
            #line default
            #line hidden
, 2680), false)
);

WriteLiteral("></script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
