#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtricate.Service.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ProductIndex.cshtml"
    using Xtricate.Web.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ProductIndex : Xtricate.Web.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




            
            #line 5 "..\..\Pages\ProductIndex.cshtml"
  
    Layout = new LayoutPage();
    Scripts = new[] { Url.To("/js-treegrid") };
    Stylesheets = new[] { Url.To("/css-treegrid") };
    Title = "Products";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row show-grid\">\r\n    <div class=\"col-md-4\"><button id=\"refresh\" cla" +
"ss=\"btn btn-default btn-sm\" data-bind=\"enabled: !isLoading()\">Refresh</button></" +
"div>\r\n    <div class=\"col-md-4\"><span data-bind=\"visible: isLoading\" class=\"glyp" +
"hicon glyphicon-refresh glyphicon-spin\"></span></div>\r\n    <div class=\"col-md-4\"" +
">&nbsp;</div>\r\n</div>\r\n\r\n<table class=\"table tree\">\r\n    <thead>\r\n        <tr>\r\n" +
"            <th>Cat</th>\r\n            <th>Id</th>\r\n            <th>Name</th>\r\n  " +
"          <th>Sku</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody data-bind=\"templ" +
"ate: { foreach: products }\">\r\n        <tr>\r\n            <td><span class=\"treegri" +
"d-expander glyphicon glyphicon-chevron-down\"></span>Category</td>\r\n            <" +
"td data-bind=\"text: id\"></td>\r\n            <td data-bind=\"text: name\"></td>\r\n   " +
"         <td data-bind=\"text: sku\"></td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r" +
"\n\r\n<script type=\"text/javascript\">\r\n    var data = [];\r\n    var viewModel = {\r\n " +
"       isLoading: ko.observable(false),\r\n        products: ko.observableArray(da" +
"ta)\r\n    };\r\n    ko.applyBindings(viewModel);\r\n\r\n    $(document).ready(function " +
"() {\r\n        Refresh();\r\n    });\r\n\r\n    $(\'#refresh\').click(function () {\r\n    " +
"    Refresh();\r\n        $(\'.tree\').treegrid();\r\n    });\r\n\r\n    function Refresh(" +
") {\r\n        viewModel.products(null);\r\n        viewModel.isLoading(true);\r\n    " +
"    $.getJSON(\"/api/products\", function (data) {\r\n            //console.log(data" +
");\r\n            viewModel.isLoading(false);\r\n            viewModel.products(data" +
");\r\n        });\r\n    };\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
